name: marp
on:
   push:
     branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: index.md -o dist/index.html
        env:
          MARP_USER: root:root

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
